# Generated by Django 4.1.4 on 2023-02-01 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='کد')),
                ('pos', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('permission', models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی')),
            ],
            options={
                'verbose_name': 'آزمایشگاه',
                'verbose_name_plural': 'آزمایشگاه ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LabPWModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encode_pw', models.TextField(verbose_name='رمزعبور')),
            ],
            options={
                'verbose_name': 'رمزعبور مرکز آزمایشگاه',
                'verbose_name_plural': 'رمز عبور های مراکز آزمایشگاه',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LabResultCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی آزمایش',
                'verbose_name_plural': 'دسته بندی آزمایش ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LabResultModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آزمایش')),
                ('result', models.CharField(max_length=255, verbose_name='جواب آزمایش')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نتیجه')),
            ],
            options={
                'verbose_name': 'جواب آزمایش',
                'verbose_name_plural': 'جواب آزمایش ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SonographyCenterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='کد')),
                ('pos', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('permission', models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی')),
            ],
            options={
                'verbose_name': 'مرکز سونوگرافی',
                'verbose_name_plural': 'مراکز سونوگرافی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SonographyPWModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encode_pw', models.TextField(verbose_name='رمزعبور')),
            ],
            options={
                'verbose_name': 'رمزعبور مرکز سونوگرافی',
                'verbose_name_plural': 'رمز عبور های مراکز سونوگرافی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SonographyResultModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('result', models.CharField(max_length=255, verbose_name='جواب آزمایش')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نتیجه')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_api.sonographycentermodel', verbose_name='مرکز سونوگرافی')),
            ],
            options={
                'verbose_name': 'نتیجه سونوگرافی',
                'verbose_name_plural': 'نتایج سونوگرافی ها',
                'ordering': ['-id'],
            },
        ),
    ]
