# Generated by Django 4.1.4 on 2022-12-13 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import extentions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_code', models.BigIntegerField(verbose_name='کد نظام پزشکی')),
                ('position', models.TextField(blank=True, max_length=500, null=True, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExprementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('exprement', 'آزمایشگاه'), ('ctscan', 'تصویربرداری-سی تی اسکن'), ('radiography_simple', 'تصویربرداری-رادیوگرافی ساده'), ('radiography_special', 'تصویربرداری-رادیوگرافی تخصصی'), ('mamography', 'تصویربرداری-ماموگرافی'), ('sonography', 'تصویربرداری-سونوگرافی')], max_length=255, verbose_name='نوع')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('pos', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TitleSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تخصص')),
            ],
            options={
                'verbose_name': 'عنوان تخصص',
                'verbose_name_plural': 'عناوین تخصص\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExprimentResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exprement', 'آزمایشگاه'), ('ctscan', 'تصویربرداری-سی تی اسکن'), ('radiography_simple', 'تصویربرداری-رادیوگرافی ساده'), ('radiography_special', 'تصویربرداری-رادیوگرافی تخصصی'), ('mamography', 'تصویربرداری-ماموگرافی'), ('sonography', 'تصویربرداری-سونوگرافی')], max_length=20, verbose_name='نوع نتیجه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آزمایش')),
                ('result', models.CharField(max_length=255, verbose_name='جواب آزمایش')),
                ('image', models.ImageField(upload_to=extentions.utils.expriment_result_image_pat, verbose_name='تصویر آزمایش')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نتیجه')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.exprementmodel', verbose_name='آزمایشگاه')),
            ],
            options={
                'verbose_name': 'نتیجه آزمایش و تصویربرداری',
                'verbose_name_plural': 'نتیجه آزمایش ها و تصویربرداری ها',
                'ordering': ['-id'],
            },
        ),
    ]
