# Generated by Django 4.1.4 on 2022-12-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exprimentresultmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='skill_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.titleskillmodel', verbose_name='عنوان تخصص'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='units',
            field=models.ManyToManyField(to='app_api.exprementmodel', verbose_name='آزمایشگاه ها'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
