# Generated by Django 4.1.4 on 2022-12-14 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_patientmodel_remove_user_age_remove_user_gender_and_more'),
        ('app_api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='کد')),
                ('pos', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'آزمایشگاه',
                'verbose_name_plural': 'آزمایشگاه ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LabResultCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'جواب آزمایش',
                'verbose_name_plural': 'جواب آزمایش ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LabResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آزمایش')),
                ('result', models.CharField(max_length=255, verbose_name='جواب آزمایش')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نتیجه')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_api.labresultcategorymodel', verbose_name='دسته بندی')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_api.labmodel', verbose_name='آزمایشگاه')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_auth.patientmodel', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'آزمایشگاه',
                'verbose_name_plural': 'آزمایشگاه ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SonographyCenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='کد')),
                ('pos', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'مرکز سونوگرافی',
                'verbose_name_plural': 'مراکز سونوگرافی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SonographyResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255, verbose_name='جواب آزمایش')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نتیجه')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_api.sonographycentermodel', verbose_name='مرکز سونوگرافی')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_auth.patientmodel', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نتیجه سونوگرافی',
                'verbose_name_plural': 'نتایج سونوگرافی ها',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='exprimentresultmodel',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='exprimentresultmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoctorModel',
        ),
        migrations.DeleteModel(
            name='ExprementModel',
        ),
        migrations.DeleteModel(
            name='ExprimentResultModel',
        ),
        migrations.DeleteModel(
            name='TitleSkillModel',
        ),
    ]
