# Generated by Django 4.1.4 on 2023-02-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonographypwmodel',
            name='sono',
        ),
        migrations.DeleteModel(
            name='LabPWModel',
        ),
        migrations.DeleteModel(
            name='SonographyPWModel',
        ),
    ]
