# Generated by Django 4.1.4 on 2022-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_labmodel_labresultcategorymodel_labresultmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresultcategorymodel',
            options={'ordering': ['-id'], 'verbose_name': 'دسته بندی آزمایش', 'verbose_name_plural': 'دسته بندی آزمایش ها'},
        ),
        migrations.AlterModelOptions(
            name='labresultmodel',
            options={'ordering': ['-id'], 'verbose_name': 'جواب آزمایش', 'verbose_name_plural': 'جواب آزمایش ها'},
        ),
        migrations.AddField(
            model_name='labmodel',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی'),
        ),
        migrations.AddField(
            model_name='sonographycentermodel',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی'),
        ),
    ]
