# Generated by Django 4.1.4 on 2023-02-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_remove_sonographypwmodel_sono_delete_labpwmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labmodel',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='sonographycentermodel',
            name='permission',
        ),
    ]
