# Generated by Django 4.1.4 on 2023-02-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_remove_labmodel_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonographyresultmodel',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان آزمایش'),
        ),
    ]
