# Generated by Django 4.1.4 on 2023-02-20 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_sonographyresultmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultSUBCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'زیر دسته بندی آزمایش',
                'verbose_name_plural': 'زیر دسته بندی آزمایش ها',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='labresultmodel',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_api.labresultsubcategorymodel', verbose_name='زیر دسته بندی'),
        ),
    ]
