# Generated by Django 4.1.4 on 2023-02-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_labresultsubcategorymodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labresultsubcategorymodel',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='labresultsubcategorymodel',
            name='title_fa',
        ),
    ]
