# Generated by Django 4.1.4 on 2023-03-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_rename_title_en_labresultsubcategorymodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresultsubcategorymodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_api.labresultcategorymodel', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='labresultmodel',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='زیر دسته بندی'),
        ),
    ]
