# Generated by Django 4.1.4 on 2022-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_patientmodel_remove_user_age_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی'),
        ),
        migrations.AddField(
            model_name='managermodel',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دسترسی'),
        ),
    ]
