# Generated by Django 4.1.4 on 2022-12-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_doctormodel_permission_managermodel_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='managermodel',
            name='permission',
        ),
    ]
